# -*- coding: utf-8 -*-
"""Untitled3.ipynb
Automatically generated by Colab.
Original file is located at
    https://colab.research.google.com/drive/1JwjM5Zc_ccAl7GEYpBIrG9q9EBNXk_Xw
"""
import pandas as pd
from sklearn.linear_model import LogisticRegression
import streamlit as sl
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
df = pd.read_csv(os.path.join(BASE_DIR, "insurance.csv"))
sl.set_page_config(page_title="Insurance Prediction", page_icon="insurance.jpg", layout="wide")

# =================================================================
# 👨‍💻 ABOUT THE DEVELOPER — Sidebar Profile Card
# =================================================================
sl.markdown(
    """
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');

    #dev-profile-card {
        font-family: 'Poppins', sans-serif;
        border-radius: 18px;
        padding: 2px;
        background: linear-gradient(135deg, #ff6a3d, #ffb347, #4C7DF5, #ff6a3d);
        background-size: 300% 300%;
        animation: gradientShift 6s ease infinite;
        margin-bottom: 14px;
    }

    @keyframes gradientShift {
        0% { background-position: 0% 50%; }
        50% { background-position: 100% 50%; }
        100% { background-position: 0% 50%; }
    }

    #dev-profile-inner {
        background: #14141f;
        border-radius: 16px;
        padding: 18px 16px 16px 16px;
        text-align: center;
    }

    #dev-avatar {
        width: 64px;
        height: 64px;
        border-radius: 50%;
        margin: 0 auto 10px auto;
        display: flex;
        align-items: center;
        justify-content: center;
        font-family: 'Poppins', sans-serif;
        font-weight: 700;
        font-size: 22px;
        color: white;
        background: linear-gradient(135deg, #4C7DF5, #ff6a3d);
        box-shadow: 0 0 0 3px rgba(255,255,255,0.08);
    }

    #dev-profile-inner h3 {
        color: #ffffff;
        font-size: 17px;
        font-weight: 700;
        margin: 4px 0 2px 0;
    }

    #dev-profile-inner .tagline {
        font-family: 'JetBrains Mono', monospace;
        color: #ffb347;
        font-size: 11.5px;
        margin-bottom: 10px;
    }

    #dev-profile-inner .edu {
        font-family: 'JetBrains Mono', monospace;
        color: #9d9db0;
        font-size: 10.5px;
        line-height: 1.5;
        margin-bottom: 12px;
        padding: 0 4px;
    }

    #dev-profile-inner .badge-row {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 6px;
        margin-bottom: 4px;
    }

    #dev-profile-inner .badge-row a {
        text-decoration: none;
        font-family: 'JetBrains Mono', monospace;
        font-size: 11px;
        color: #14141f;
        background: #ffffff;
        padding: 5px 10px;
        border-radius: 20px;
        font-weight: 500;
        transition: transform 0.18s ease, background 0.18s ease;
        display: inline-block;
    }

    #dev-profile-inner .badge-row a:hover {
        transform: translateY(-2px);
        background: #ffb347;
    }
    </style>

    <div id="dev-profile-card">
        <div id="dev-profile-inner">
            <div id="dev-avatar">AA</div>
            <h3>Aditya Agarwal 🚀</h3>
            <div class="tagline">// Data Science &amp; ML Enthusiast</div>
            <div class="edu">
                🎓 B.Tech, Computer Science Engineering<br/>
                Shri Ramswaroop Memorial College of<br/>
                Engineering &amp; Management, Lucknow
            </div>
            <div class="badge-row">
                <a href="mailto:aasblko@gmail.com" target="_blank">📧 Email</a>
                <a href="https://www.linkedin.com/in/aditya-agarwal-48348126b/" target="_blank">💼 LinkedIn</a>
                <a href="https://github.com/DragonWarrior9842" target="_blank">🐙 GitHub</a>
                <a href="https://www.instagram.com/adityaagarwal67/" target="_blank">🌐 Instagram</a>
            </div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

with sl.sidebar:
    with sl.expander("ℹ️ More about this project"):
        sl.write(
            "Built as a hands-on demo of **Logistic Regression** — predicting "
            "insurance uptake from age alone. Made while learning core ML "
            "concepts from scratch, one small project at a time."
        )

sl.markdown(
    """
    <style>
    .stButton > button {
        background-color: #4C7DF5;
        color: white;
        border: none;
        border-radius: 8px;
        padding: 0.5em 1.5em;
        font-weight: 600;
    }
    .stButton > button:hover {
        background-color: #3D66D6;
        color: white;
    }
    .stSuccess {
        background-color: rgba(45, 191, 108, 0.15);
        border: 1px solid #2DBF6C;
    }
    </style>
    """,
    unsafe_allow_html=True,
)
col_logo, col_title = sl.columns([1, 5])
with col_logo:
    sl.image(os.path.join(BASE_DIR, "insurance.jpg"), width=400)
with col_title:
    sl.title("Insurance Prediction")
    sl.caption("A simple ML demo that predicts insurance need based on age.")
sl.subheader("Prediction of Insurance Necessity With Age")
sl.dataframe(df)
sl.subheader("Age vs. Insurance Uptake")
sl.scatter_chart(df, x="age", y="bought_insurance")
x=df[["age"]]
y=df["bought_insurance"]
logreg = LogisticRegression()
logreg.fit(x,y)
sl.caption(f"Model accuracy on training data: {logreg.score(x,y):.0%}")
sl.subheader("What does the project do?")
sl.write("It's a small web app that guesses whether someone is likely to buy insurance, based only on their age. You type in an age, click a button, and it tells you \"Yes\" or \"No\" along with how confident it is.")
sl.subheader("Enter the Age to Suggest")
col_input, col_result = sl.columns([1, 2])
with col_input:
    age = sl.number_input("Age", value=18, max_value=60, min_value=3)
    suggest = sl.button("Suggestion")
if suggest:
     prediction = logreg.predict([[age]])
     if prediction[0] == 1:
        result = "Yes"
        sl.success(f"{result}, you need to take insurance")
     else:
        result = "No"
        sl.success(f"{result}, you don't need to take insurance")
sl.markdown("---")
sl.title("Description:")
sl.subheader("The Method: Logistic Regression")
sl.write("This is a simple, well-known machine learning technique used for yes/no (or 0/1) predictions — not to be confused with regular \"regression\" which predicts numbers like prices. Here, it predicts a category: bought insurance (1) or didn't (0).")
sl.subheader("Formula of the Logistic Regression:")
sl.latex(r"f(x) = \frac{1}{1 + e^{-x}}")
