# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwjM5Zc_ccAl7GEYpBIrG9q9EBNXk_Xw
"""

import pandas as pd

from sklearn.linear_model import LogisticRegression

import streamlit as sl

df = pd.read_csv("insurance_data.csv")

sl.set_page_config(page_title="Insurance Prediction", page_icon="insurance.jpg", layout="wide")

with sl.sidebar:
    sl.header("About the Developer:")
    sl.write("**Aditya Agarwal**")
    sl.write("Data Science / ML Enthusiast")
    sl.write("Currently a Student of Shri Ramswaroop Memorial College of Engineering and Management, Lucknow")
    sl.write("Pursuing Bachelor of Technology in Computer Science Engineering")
    
    sl.markdown("---")
    
    sl.markdown("📧 [Email](mailto:aasblko@gmail.com)")
    sl.markdown("💼 [LinkedIn](https://www.linkedin.com/in/aditya-agarwal-48348126b/)")
    sl.markdown("🐙 [GitHub](https://github.com/DragonWarrior9842)")
    sl.markdown("🌐 [Instagram](https://www.instagram.com/adityaagarwal67/)")

sl.markdown(
    """
    <style>
    .stButton > button {
        background-color: #4C7DF5;
        color: white;
        border: none;
        border-radius: 8px;
        padding: 0.5em 1.5em;
        font-weight: 600;
    }
    .stButton > button:hover {
        background-color: #3D66D6;
        color: white;
    }
    .stSuccess {
        background-color: rgba(45, 191, 108, 0.15);
        border: 1px solid #2DBF6C;
    }
    </style>
    """,
    unsafe_allow_html=True,
)

col_logo, col_title = sl.columns([1, 5])
with col_logo:
    sl.image("insurance.jpg", width=400)
with col_title:
    sl.title("Insurance Prediction")
    sl.caption("A simple ML demo that predicts insurance need based on age.")

sl.subheader("Prediction of Insurance Necessity With Age")
sl.dataframe(df)

sl.subheader("Age vs. Insurance Uptake")
sl.scatter_chart(df, x="age", y="bought_insurance")

x=df[["age"]]

y=df["bought_insurance"]

logreg = LogisticRegression()

logreg.fit(x,y)

sl.caption(f"Model accuracy on training data: {logreg.score(x,y):.0%}")

sl.subheader("What does the project do?")
sl.write("It's a small web app that guesses whether someone is likely to buy insurance, based only on their age. You type in an age, click a button, and it tells you \"Yes\" or \"No\" along with how confident it is.")

sl.subheader("Enter the Age to Suggest")

col_input, col_result = sl.columns([1, 2])

with col_input:
    age = sl.number_input("Age", value=18, max_value=60, min_value=3)
    suggest = sl.button("Suggestion")

if suggest:
     prediction = logreg.predict([[age]])

     if prediction[0] == 1:
        result = "Yes"
        sl.success(f"{result}, you need to take insurance")
     else:
        result = "No"
        sl.success(f"{result}, you don't need to take insurance")
sl.markdown("---")
sl.title("Description:")
sl.subheader("The Method: Logistic Regression")
sl.write("This is a simple, well-known machine learning technique used for yes/no (or 0/1) predictions — not to be confused with regular \"regression\" which predicts numbers like prices. Here, it predicts a category: bought insurance (1) or didn't (0).")
sl.subheader("Formula of the Logistic Regression:")
sl.latex(r"f(x) = \frac{1}{1 + e^{-x}}")
